/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 首页聚合数据 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 首页数据。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HomeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergency/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 急救分类列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 急救分类列表。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmergencyCategoryListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergency/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 急救文章列表 */
        get: {
            parameters: {
                query?: {
                    categoryId?: string;
                    keyword?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 急救文章列表。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmergencyArticleListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergency/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 急救文章详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 急救文章详情。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmergencyArticleDetailResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hospitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 宠物医院列表 */
        get: {
            parameters: {
                query?: {
                    keyword?: string;
                    longitude?: number;
                    latitude?: number;
                    radius?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 宠物医院列表。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HospitalListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hospitals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 宠物医院详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 宠物医院详情。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HospitalDetailResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lost-pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 寻宠列表 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 寻宠列表。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LostPetPageResponse"];
                    };
                };
            };
        };
        put?: never;
        /** 发布寻宠 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateLostPetRequest"];
                };
            };
            responses: {
                /** @description 发布成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LostPetDetailResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lost-pets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 寻宠详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 寻宠详情。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LostPetDetailResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adoptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 领养列表 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 领养列表。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdoptionPageResponse"];
                    };
                };
            };
        };
        put?: never;
        /** 发布领养 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAdoptionRequest"];
                };
            };
            responses: {
                /** @description 发布成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdoptionDetailResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adoptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 领养详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 领养详情。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdoptionDetailResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 社区帖子列表 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 社区帖子列表。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityPostPageResponse"];
                    };
                };
            };
        };
        put?: never;
        /** 发布帖子 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePostRequest"];
                };
            };
            responses: {
                /** @description 发布成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityPostDetailResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 社区帖子详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 社区帖子详情。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityPostDetailResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/posts/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发表评论 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCommentRequest"];
                };
            };
            responses: {
                /** @description 评论成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 登录成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 当前用户信息。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfileResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的宠物列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 我的宠物列表。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PetProfileListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 创建宠物档案 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePetRequest"];
                };
            };
            responses: {
                /** @description 创建成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PetProfileResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新宠物档案 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePetRequest"];
                };
            };
            responses: {
                /** @description 更新成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PetProfileResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 收藏或取消收藏 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FavoriteRequest"];
                };
            };
            responses: {
                /** @description 操作成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmptyResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传文件 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        /** @enum {string} */
                        scene?: "avatar" | "pet" | "lost" | "adoption" | "community";
                    };
                };
            };
            responses: {
                /** @description 上传成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理员登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminLoginRequest"];
                };
            };
            responses: {
                /** @description 登录成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户管理列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 用户列表。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserPageResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/hospitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 医院管理列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 医院管理列表。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HospitalListResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** 新增医院 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HospitalMutationRequest"];
                };
            };
            responses: {
                /** @description 创建成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HospitalDetailResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/hospitals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除医院 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmptyResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** 更新医院 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HospitalMutationRequest"];
                };
            };
            responses: {
                /** @description 更新成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HospitalDetailResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/lost-pets/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 寻宠审核 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuditRequest"];
                };
            };
            responses: {
                /** @description 审核成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmptyResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/adoptions/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 领养审核 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuditRequest"];
                };
            };
            responses: {
                /** @description 审核成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmptyResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/community/posts/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 社区帖子审核 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuditRequest"];
                };
            };
            responses: {
                /** @description 审核成功。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmptyResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EmptyResponse: {
            /** @example 200 */
            code: number;
            /** @example 操作成功 */
            message: string;
            /** @example null */
            data: unknown;
        };
        ErrorResponse: {
            /** @example 400 */
            code: number;
            /** @example 请求参数错误 */
            message: string;
            /** @example null */
            data: unknown;
        };
        HomeResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["HomeSummary"];
        };
        HomeSummary: {
            emergencyEntrances: components["schemas"]["QuickEntry"][];
            hospitalEntrance: components["schemas"]["QuickEntry"];
            lostPetEntrance: components["schemas"]["QuickEntry"];
        };
        QuickEntry: {
            title: string;
            path: string;
            iconUrl?: string;
        };
        EmergencyCategoryListResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["EmergencyCategory"][];
        };
        EmergencyCategory: {
            id: string;
            name: string;
            sort?: number;
        };
        EmergencyArticleListResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["EmergencyArticleSummary"][];
        };
        EmergencyArticleDetailResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["EmergencyArticleDetail"];
        };
        EmergencyArticleSummary: {
            id: string;
            title: string;
            categoryId: string;
            coverUrl?: string;
            summary?: string;
        };
        EmergencyArticleDetail: components["schemas"]["EmergencyArticleSummary"] & {
            content: string;
            riskNotice?: string;
        };
        HospitalListResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["Hospital"][];
        };
        HospitalDetailResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["Hospital"];
        };
        Hospital: {
            id: string;
            name: string;
            phone?: string;
            address: string;
            /** Format: double */
            longitude?: number;
            /** Format: double */
            latitude?: number;
            openingHours?: string;
        };
        HospitalMutationRequest: {
            name: string;
            phone?: string;
            address: string;
            /** Format: double */
            longitude?: number;
            /** Format: double */
            latitude?: number;
            openingHours?: string;
        };
        PageMeta: {
            page: number;
            pageSize: number;
            total: number;
        };
        LostPetPageResponse: components["schemas"]["EmptyResponse"] & {
            data?: {
                list: components["schemas"]["LostPet"][];
                page: number;
                pageSize: number;
                total: number;
            };
        };
        LostPetDetailResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["LostPet"];
        };
        LostPet: {
            id: string;
            petName: string;
            /** Format: date-time */
            lostTime: string;
            lostAddress?: string;
            contactPhone: string;
            description?: string;
            imageUrls?: string[];
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "closed";
        };
        CreateLostPetRequest: {
            petName: string;
            /** Format: date-time */
            lostTime: string;
            lostAddress?: string;
            contactPhone: string;
            description?: string;
            imageUrls?: string[];
        };
        AdoptionPageResponse: components["schemas"]["EmptyResponse"] & {
            data?: {
                list: components["schemas"]["Adoption"][];
                page: number;
                pageSize: number;
                total: number;
            };
        };
        AdoptionDetailResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["Adoption"];
        };
        Adoption: {
            id: string;
            title: string;
            contactPhone: string;
            description?: string;
            imageUrls?: string[];
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "closed";
        };
        CreateAdoptionRequest: {
            title: string;
            contactPhone: string;
            description?: string;
            imageUrls?: string[];
        };
        CommunityPostPageResponse: components["schemas"]["EmptyResponse"] & {
            data?: {
                list: components["schemas"]["CommunityPost"][];
                page: number;
                pageSize: number;
                total: number;
            };
        };
        CommunityPostDetailResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["CommunityPost"];
        };
        CommunityPost: {
            id: string;
            title: string;
            content: string;
            imageUrls?: string[];
            /** @enum {string} */
            status: "pending" | "approved" | "rejected";
        };
        CreatePostRequest: {
            title: string;
            content: string;
            imageUrls?: string[];
        };
        CreateCommentRequest: {
            content: string;
        };
        CommentResponse: components["schemas"]["EmptyResponse"] & {
            data?: {
                id: string;
                content: string;
            };
        };
        LoginRequest: {
            phone: string;
            /** Format: password */
            password: string;
        };
        AdminLoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: components["schemas"]["EmptyResponse"] & {
            data?: {
                token: string;
                user: components["schemas"]["UserProfile"];
            };
        };
        UserProfileResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["UserProfile"];
        };
        UserProfile: {
            id: string;
            nickname: string;
            avatarUrl?: string;
            /** @enum {string} */
            role?: "user" | "admin";
        };
        PetProfileListResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["PetProfile"][];
        };
        PetProfileResponse: components["schemas"]["EmptyResponse"] & {
            data?: components["schemas"]["PetProfile"];
        };
        PetProfile: {
            id: string;
            name: string;
            /** @enum {string} */
            species: "dog" | "cat" | "other";
            breed?: string;
            /** Format: date */
            birthday?: string;
            avatarUrl?: string;
        };
        CreatePetRequest: {
            name: string;
            /** @enum {string} */
            species: "dog" | "cat" | "other";
            breed?: string;
            /** Format: date */
            birthday?: string;
            avatarUrl?: string;
        };
        UpdatePetRequest: {
            name?: string;
            /** @enum {string} */
            species?: "dog" | "cat" | "other";
            breed?: string;
            /** Format: date */
            birthday?: string;
            avatarUrl?: string;
        };
        FavoriteRequest: {
            /** @enum {string} */
            targetType: "emergencyArticle" | "hospital" | "lostPet" | "adoption" | "communityPost";
            targetId: string;
            favorited: boolean;
        };
        UploadResponse: components["schemas"]["EmptyResponse"] & {
            data?: {
                fileUrl: string;
                fileKey?: string;
                contentType?: string;
            };
        };
        AdminUserPageResponse: components["schemas"]["EmptyResponse"] & {
            data?: {
                list: components["schemas"]["UserProfile"][];
                page: number;
                pageSize: number;
                total: number;
            };
        };
        AuditRequest: {
            /** @enum {string} */
            status: "approved" | "rejected";
            reason?: string;
        };
    };
    responses: {
        /** @description 未登录或 Token 无效。 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 无权限。 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 数据不存在。 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        PathId: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
